### ISSUE TITLE
generating factories with tenancyforlaravel

### ISSUE THREAD

**Issue by chrillep** [TheDoctor0/laravel-factory-generator#18]
when using tenancyforlaravel there are multiple db connections.

So when trying to find the tables connected to a model it needs to know in which context to look.
central and tenants have different db:s.
Ive solved this by switching app db when generating models on central and tenant.

- central models -> central db
- tenant models -> tenant db

it would be nice if the generator understood it :) 

https://tenancyforlaravel.com/docs/v3/multi-database-tenancy
https://tenancyforlaravel.com/docs/v3/migrations

ref: https://github.com/dedoc/scramble/issues/81#issuecomment-1355584119

**Comment by chrillep** [comment]
this works but  need som love
```php
        if (! $columns) {
            $tenantModel = $this->laravel['config']->get('tenancy.tenant_model', null);
            if ($tenantModel ) {
                tenancy()->initialize($tenantModel::first());
                $table = $model->getConnection()->getTablePrefix() . $model->getTable();
                $schema = $model->getConnection()->getDoctrineSchemaManager();
                $columns = $schema->listTableColumns($table, $database);
            }
        }
```
but first we should check if tenancy even exists.
and after getting columns maybe switch back to central context. not sure :)

**Comment by TheDoctor0** [comment]
Hey @chrillep!

I must admit that I'm a little hesitant about adding package-specific code just to support Tenancy for Laravel as in the long run it will create a maintenance burden.

I'm considering adding optional functions (hooks) for models that can be defined and if exist they will be executed before and after scanning the given model. That way you will be able to initialize and later end the tenancy context without me having to include a specific code for it in the factory generator. I'll try to implement it this evening, so stay tuned.

**Comment by TheDoctor0** [comment]
@chrillep, I added two optional functions that can be used inside the models: `factoryGeneratorInit` and `factoryGeneratorEnd`.

Based on the snippet that you provided earlier you probably just need to add a few lines to your models:
```php
public function factoryGeneratorInit(): void
{
	tenancy()->initialize(config('tenancy.tenant_model')::first());
}

public function factoryGeneratorInit(): void
{
	tenancy()->end();
}
```

I did not tag the new version yet, so you will need to install it with `composer require thedoctor0/laravel-factory-generator dev-master` to test this solution.

**Comment by chrillep** [comment]
> I must admit that I'm a little hesitant about adding package-specific code just to support Tenancy for Laravel as in the long run it will create a maintenance burden.

yes i totally understnad that. if there is some other way to switch the db connection im open for it, i just wanted to voice what was happening :) 
ill try the hooks out. and maybe add a parent for all models that are used in a tenant context

**Comment by TheDoctor0** [comment]
Hye @chrillep. Did you already test the factory generation with hooks for models in the tenant context?

**Comment by chrillep** [comment]
no sry havent made time for it. ill try and test it during the week since i wanted it 😅

**Comment by chrillep** [comment]
omg sry. gonna test it today cuz i actually need to do this for work :)

**Comment by chrillep** [comment]
@TheDoctor0 works! :) ty
