### ISSUE TITLE
When running tests getting the error Doctrine\DBAL\DBALException

### ISSUE THREAD

**Issue by CalumChamberlain** [TheDoctor0/laravel-factory-generator#2]
When running my tests I get this error until I uninstall the package

```
   Doctrine\DBAL\DBALException

  Type enum already exists.

  at vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php:262
    258▕      * @return DBALException
    259▕      */
    260▕     public static function typeExists($name)
    261▕     {
  ➜ 262▕         return new self('Type ' . $name . ' already exists.');
    263▕     }
    264▕
    265▕     /**
    266▕      * @param string $name

      +3 vendor frames
  4   [internal]:0
      TheDoctor0\LaravelFactoryGenerator\Console\GenerateFactoryCommand::__construct()

```

**Comment by TheDoctor0** [comment]
Hi Calum.
Do you have any other library that may register `enum` type for `doctrine/dbal` or do you register it in your app?

**Comment by TheDoctor0** [comment]
I can solve this issue by aliasing registered custom type to something else than just `enum`.
I'll make a change in a minute and release 1.0.1 version with fix included.

**Comment by dpwilhelmsen** [comment]
Hello. I know this is closed but I wanted to add some additional information. I'm not sure exactly what was triggering it but I ran into the same issue when running a test for an artisan command. Specifically, I would make the following call:

`$this->app['Illuminate\Contracts\Console\Kernel']->registerCommand($command);`

And it would eventually throw the error. My guess is for some reason it was trying to re-register the command? Either way, what resolved it for me was updating `GenerateFactoryCommand.php` with this:

```php
if (!Type::hasType('customEnum')) {
    Type::addType('customEnum', EnumType::class);
}
```

I'm not sure if I'll have time to create an isolated sample application for the issue, but perhaps this will shed some light on it. Thanks for updating and maintaining this package!
