### ISSUE TITLE
Unable to correctly resolve path to database/factories directory

### ISSUE THREAD

**Issue by palypster** [TheDoctor0/laravel-factory-generator#23]
I'm having problems with generating factories - app is not able to resolve the path to the database folder correctly.

I've debugged to problem and found out, that you have hardoced the path to `database/factories` without proberly using Laravel's `base_path()` helper.

So instead of using:
`$filename = "database/factories/{$class}Factory.php";`
it should be (in my opinion) wrapped like this:
`$filename = base_path("database/factories/{$class}Factory.php");`

Would you mind changing this? It's a very easy fix.

Note that the path is hard-coded in three different places, so this needs to be reflected in all three places.

Many thanks

**Comment by TheDoctor0** [comment]
Hello @palypster!
I just fixed that in https://github.com/TheDoctor0/laravel-factory-generator/commit/7ee56e4229b78d5f6274a4649819b2bca0bd56e3 and will make a release in a moment.
