### ISSUE TITLE
Error: model is not configured properly!

### ISSUE THREAD

**Issue by warmwhisky** [TheDoctor0/laravel-factory-generator#24]
When I try to run `php artisan generate:factory User Companies`
I get the following error `Database driver (mysql) for App\Models\Companies model is not configured properly!`

I get the same error on all models when running `php artisan generate:factory`

Companies migration
```php
Schema::create('companies', function (Blueprint $table) {
    $table->id();
    $table->string('company_name', 100);
    $table->unsignedBigInteger('user_id')->index();
    $table->timestamps();
});

Schema::table('companies', function (Blueprint $table) {
    $table->foreign('user_id')->references('id')->on('users')->onDelete('cascade');
});
```

Companies Model
```php
class Companies extends Model
{
    use HasFactory;
    public $guarded = [];

    public function clusters(): HasMany {
        return $this->hasMany(PosClusters::class);
    }

    public function user(): BelongsTo {
        return $this->belongsTo(User::class);
    }
}
```

**Comment by TheDoctor0** [comment]
Hello @warmwhisky.
The generator fetched a table schema from the database.
This error clearly suggests that the database connection cannot be established, so please check the database connection credentials.

**Comment by warmwhisky** [comment]
@TheDoctor0 I believe the connection is fine as I can run migrations and also log in with the user.

Edit: I am using WSL with Docker in Windows 10

**Comment by TheDoctor0** [comment]
@warmwhisky that would mean that [this line](https://github.com/TheDoctor0/laravel-factory-generator/blob/master/src/Console/GenerateFactoryCommand.php#L209) fails anyway.
I would suggest simply adding a `dd($exception)` in the `catch` closure so that you can get an actual error message for it.
