### ISSUE TITLE
Laravel 11 support

### ISSUE THREAD

**Issue by johnluxor** [TheDoctor0/laravel-factory-generator#28]
Hello, in Laravel 11 they removed dependency on doctrine/dbal and factory generator doesn't work correctly. It cannot get table structure anymore because it used DBAL before.
So there is an Exception

```
Method Illuminate\Database\MySqlConnection::getDoctrineSchemaManager does not exist.
```

in `getPropertiesFromTable:210`

**Comment by TheDoctor0** [comment]
Hey @johnluxor!

You are right, looks like I'll need to use https://laravel.com/api/8.x/Illuminate/Database/Schema/Blueprint.html#method_getColumns instead for Laravel 11.x.
I'll try to implement that in the upcoming weekend but feel free to open an PR.

**Comment by TheDoctor0** [comment]
@johnluxor done in https://github.com/TheDoctor0/laravel-factory-generator/releases/tag/1.4.0

**Comment by johnluxor** [comment]
Thank you so much!
