### ISSUE TITLE
Different namespace from --dir

### ISSUE THREAD

**Issue by bilogic** [TheDoctor0/laravel-factory-generator#4]
Hi,

Thanks for taking this up! 

I tried to specify `--dir vendor/bilogic/package/src/Models/` which did not work.
I suspect the package assumes the same namespace. Possible to specify a namespace as well?

```BASH
$ php artisan generate:factory --dir vendor/bilogic/package/src/Models/
Unable to find vendor\bilogic\package\src\Models\Transaction class!
Unable to find vendor\bilogic\package\src\Models\Customer class!
```

Perhaps allow us to specify the namespace after the folder? 
Something like `php artisan generate:factory --dir vendor/bilogic/package/src/Models/;Bilogic/Package/Models`?

Sidenote:
As for touching the `vendor` folder, they are symlinked to the packages I'm developing.
So, I kinda know what I'm doing and just trying to use this package to create factories for my packages.

**Comment by bilogic** [comment]
https://github.com/TheDoctor0/laravel-factory-generator/blob/37e2fc9e172be9bd52dbe27265189371760851cb/src/Console/GenerateFactoryCommand.php#L84-L87

Hi,

I found a quick hack to modify `$model` after line 85. I'm happy to file a PR if this is something you find acceptable. Thank you.

```
$ php artisan generate:factory --dir vendor/bilogic/package/src/Models/ --namespace Bilogic\Package\Models\
Model factory created: database/factories/Transaction.php
Model factory created: database/factories/Customer.php
```

**Comment by TheDoctor0** [comment]
Hi @bilogic,
yes, this package assumes that all models have the same namespace as the specified directory.

My question would be: Why you don't install `laravel-factory-generator` in the package that you are developing and generate factories there?

However, if you will submit a PR I'll gladly review it.

**Comment by bilogic** [comment]
Hi @TheDoctor0,

Hmm I'm not sure how to install `laravel-factory-generator` in a package. I mean, I could add it to the package's `composer.json`, but then `laravel-factory-generator` will still be installed in the Laravel project and still targeting the Laravel's namespace.

Perhaps you know a different approach? 

Let me file a PR for review. Thank you!

**Comment by TheDoctor0** [comment]
Namespace option has been added in #7.
