### ISSUE TITLE
Add support for Lumen versioning

### ISSUE THREAD

**Issue by noplanman** [TheDoctor0/laravel-factory-generator#9]
When creating the factories, the `isLaravel8OrAbove` version check always returns `false` for Lumen, as the version string is `Lumen (8.2.4) (Laravel Components ^8.0)` instead of just `8.2.4`.

Would be great to take the Lumen version into account, to generate factory classes instead of methods.

**Comment by TheDoctor0** [comment]
Hi @noplanman!
I initially wasn't really taking Lumen into consideration.
I'll come back to this in the coming days and change version detection to also support it.

**Comment by noplanman** [comment]
I just changed it to return true to generate the files, as it's a one-off for me.
But maybe others would enjoy a built-in fix.
